CREATE TABLE IF NOT EXISTS guilds (id INT UNIQUE NOT NULL, channel_id INT);

CREATE TABLE IF NOT EXISTS users (id INT UNIQUE NOT NULL, birthday TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS sys_data (id INT UNIQUE NOT NULL, daily_reset REAL);

INSERT OR IGNORE INTO sys_data (id) VALUES (0);
